### PR TITLE
Bm payment types controller

### PR DESCRIPTION
**Pull request by wlmathison**
# Description

Creating PaymentTypeController with GET, POST, PUT, and DELETE methods. Creating TestPaymentType to test all of the methods on PaymentTypeController. 

Fixes Issue # [(Issue #1 )](https://github.com/grumpy-rainbows/BangazonAPI/issues/1)

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Testing Instructions

1. `git fetch --all`
2. `git checkout bm-payment-types-controller`
3. Run the following code in a SQLQuery for BangazonAPI in Azure 
IF YOU DO NOT HAVE A CUSTOMER WITH ID of 1, then add the following or update an existing customer to have ID of 1.
`INSERT INTO Customer (FirstName, LastName) VALUES ('Joe', 'Schmo')`

THEN
`INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (22222, 'Test', 1)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (12345, 'Visa', 1)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (33333, 'Test', 1)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (55555, 'PayPal', 1)`

4. Click Run Tests on TestPaymentType.cs in TestBangazonAPI Folder

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by leahhoefling** [comment]
Wonderful testing instructions!

**Comment by leahhoefling** [comment]
Also-- please be sure to put comments including the author and purpose.

**Comment by wlmathison** [comment]
I did include Author, Purpose, and Methods on each page. Do they need to be more detailed?

**Review by greenskybluephish — APPROVED** [review]
well done sir.

**Review by AliAbdulle — APPROVED** [review]
All test pass well done Billy!

**Review by jameka23 — APPROVED** [review]
Def works. Great job, Billy!

**Pull request merged**
