### PR TITLE
Creating Order and PaymentType classes within Models folder

### PR DESCRIPTION
**Pull request by wlmathison**
# Description

Creating Order class with properties and PaymentType class with properties within the models folder.

Fixes Issue # (n/a)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. `git fetch --all`
2. `git checkout bm-creating-models`
3. check to make sure that there are models for 'Order' and 'PaymentType'. 
4. Make sure the .cs files have all the properties needed for that model and make sure the types are correct.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by leahhoefling** [comment]
Please make sure every class is documented with purpose, author, and methods.

**Review by jameka23 — COMMENTED** [review]
Looks good, just add the public Customer customer {get; set;} into both Order.cs and PaymentType.cs

**Review by jameka23 — APPROVED** [review]
it's added, and I see it

**Review by AliAbdulle — APPROVED** [review]
Looks good 👍

**Review by greenskybluephish — APPROVED** [review]

**Pull request merged**
